Repository playframework/play-java-seed.g8, pull requests merged in 2019-01, with the labels that each got.

#48 Upgrade branch 2.6.x using TemplateControl
  .travis.yml
  project/build.properties
  scripts/script-helper
  scripts/test-gradle
  scripts/test-sbt
  src/main/g8/build.sbt
  src/main/g8/project/build.properties
Labels: merge-when-green, template-control

#47 Upgrade branch 2.7.x using TemplateControl
  .travis.yml
  project/build.properties
  scripts/test-gradle
  scripts/test-sbt
  src/main/g8/build.gradle
  src/main/g8/build.sbt
  src/main/g8/project/build.properties
  src/main/g8/project/plugins.sbt
Labels: merge-when-green, template-control

#52 Upgrade branch 2.7.x using TemplateControl
  .travis.yml
  build.sbt
  project/build.properties
  project/giter8.sbt
Labels: block-merge, template-control

#54 Upgrade branch 2.6.x using TemplateControl
  src/main/g8/build.gradle
  src/main/g8/project/plugins.sbt
Labels: merge-when-green, template-control

#56 [2.6.x] Declare plugins in plugins.sbt
  build.sbt
  project/plugins.sbt
  src/main/g8/project/plugins.sbt
  src/main/g8/project/scaffold.sbt
Labels: merge-when-green

#57 Upgrade branch 2.7.x using TemplateControl
  .travis.yml
  LICENSE
  NOTICE
  src/main/g8/build.gradle
  src/main/g8/project/plugins.sbt
Labels: merge-when-green, template-control

#55 [2.7.x] Declare plugins in plugins.sbt
  project/plugins.sbt
  src/main/g8/project/plugins.sbt
  src/main/g8/project/scaffold.sbt
Labels: merge-when-green

#58 Upgrade branch 2.7.x using TemplateControl
  src/main/g8/project/plugins.sbt
Labels: merge-when-green, template-control

#61 Upgrade branch 2.6.x using TemplateControl
  .mergify.yml
  LICENSE
  NOTICE
Labels: merge-when-green, template-control

#62 Upgrade branch 2.6.x using TemplateControl
  .mergify.yml
Labels: merge-when-green
